// React-Node Chat Application/client/src/App.js
import "./App.css";
import io from "socket.io-client";
import { useState } from "react";
import Chat from "./components/Chat";

const socket = io.connect("http://localhost:3001");

function App() {
  const [student, setStudent] = useState("");
  const [studyGroup, setStudyGroup] = useState("");
  const [displayGroupChat, setDisplayGroupChat] = useState(false);

  const onJoinChat = () => {
    if (student && studyGroup) {
      socket.emit("Join Study Group", studyGroup);
      setDisplayGroupChat(true);
    }
  };

  return (
    <div className="Form">
      {!displayGroupChat ? (
        <div className="joinChatContainer">
          <h1>Kahoot!</h1>
          <input
            type="text"
            placeholder="Student Name"
            onChange={(event) => setStudent(event.target.value)}
          />
          <input
            type="text"
            placeholder="Enter PIN"
            onChange={(event) => setStudyGroup(event.target.value)}
            // onKeyDown event can be added anywhere
            // For calling joinRoom on pressing Enter
            onKeyDown={(event) => {
              event.key === "Enter" && onJoinChat();
            }}
          />
          <button onClick={onJoinChat}>Join Study Group</button>
        </div>
      ) : (
        <Chat socket={socket} student={student} studyGroup={studyGroup} />
      )}
    </div>
  );
}

export default App;

// Angular Chat Application Frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import * as io from 'socket.io-client';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  socket = io.connect('http://localhost:3001');
  student: string = '';
  studyGroup: string = '';
  displayGroupChat: boolean = false;

  onJoinChat() {
    if (this.student && this.studyGroup) {
      this.socket.emit('Join Study Group', this.studyGroup);
      this.displayGroupChat = true;
    }
  }
}

<div class="Form">
  <div *ngIf="!displayGroupChat" class="joinChatContainer">
    <h1>Kahoot!</h1>
    <input type="text" placeholder="Student Name" [(ngModel)]="student" />
    <input
      type="text"
      placeholder="Enter PIN"
      [(ngModel)]="studyGroup"
      (keydown.enter)="onJoinChat()"
    />
    <button (click)="onJoinChat()">Join Study Group</button>
  </div>

  <app-chat
    *ngIf="displayGroupChat"
    [socket]="socket"
    [student]="student"
    [studyGroup]="studyGroup"
  ></app-chat>
</div>
