// Angular Chat Application/chat-app/src/app/components/chat/chat.component.ts
import {
  Component,
  OnInit,
  OnDestroy,
  ViewChild,
  ElementRef,
  AfterViewChecked,
} from '@angular/core';
import { Input } from '@angular/core';

@Component({
  selector: 'app-chat',
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.css'],
})
export class ChatComponent implements OnInit, OnDestroy, AfterViewChecked {
  // export class ChatComponent implements OnInit, OnDestroy {
  @ViewChild('scrollContainer') private scrollContainer!: ElementRef;

  @Input() socket: any;
  @Input() username: string = '';
  @Input() room: string = '';

  // socket: any;
  // username: string = '';
  // room: string = '';
  currentMessage: string = '';
  messageList: Array<any> = [];

  constructor() {
    // this.socket.on('Receive_Message', (data: any) => {
    //   console.log('In receive message');
    //   this.messageList.push(data);
    //   console.log('List -', this.messageList);
    // });
  }

  ngOnInit() {
    console.log('In ng init');
    // You can initialize the socket connection here if not passed from parent

    // Listen for incoming messages
    this.socket.on('Receive Message', (data: any) => {
      console.log('In receive message');
      this.messageList.push(data);
      console.log('List -', this.messageList);
    });
  }

  ngAfterViewChecked() {
    // Auto-scroll to bottom
    this.scrollToBottom();
  }

  sendMessage() {
    console.log('In send msg');
    console.log('Current msg', this.currentMessage);
    if (this.currentMessage) {
      const currentTime = new Date();
      const messageData = {
        room: this.room,
        author: this.username,
        message: this.currentMessage,
        time: currentTime.getHours() + ':' + currentTime.getMinutes(),
      };
      console.log('Message Data -', messageData);
      this.socket.emit('Send Message', messageData);
      this.messageList.push(messageData);
      this.currentMessage = '';
    }
  }

  scrollToBottom(): void {
    this.scrollContainer.nativeElement.scrollTop =
      this.scrollContainer.nativeElement.scrollHeight;
  }

  ngOnDestroy() {
    // Clean up any listeners to prevent memory leaks
    this.socket.off('Receive Message');
  }
}

<div class="chat-window">
    <div class="chat-header">
      <p>Live Chat</p>
    </div>
    <div class="chat-body" #scrollContainer>
      <div *ngFor="let messageContent of messageList" class="message" [ngClass]="{'you': username === messageContent.author, 'other': username !== messageContent.author}">
        <div>
          <div class="message-content">
            <p>{{messageContent.message}}</p>
          </div>
          <div class="message-meta">
            <p id="time">{{messageContent.time}}</p>
            <p id="author">{{messageContent.author}}</p>
          </div>
        </div>
      </div>
    </div>
    <div class="chat-footer">
      <!-- <input type="text" [value]="currentMessage" placeholder="Hey..." (input)="currentMessage = ($event.target as HTMLInputElement).value"
      (keydown.enter)="sendMessage()" /> -->
      <input type="text" [value]="currentMessage" placeholder="Hey..." [(ngModel)]="currentMessage" (keydown.enter)="sendMessage()" />
      <button (click)="sendMessage()">&#9658;</button>
    </div>
  </div>

// React-Node Chat Application/client/src/components/Chat.js
// import React, { useEffect, useState } from "react";

// function Chat({ socket, username, room }) {
//   const [message, setMessage] = useState("");
//   const [messageList, setMessageList] = useState([]);

//   const onMessageSent = async () => {
//     if (message) {
//       const currentTime = new Date(Date.now());
//       const messageData = {
//         room: room,
//         user: username,
//         message: message,
//         time: currentTime.getHours() + ":" + currentTime.getMinutes(),
//       };
//       //   console.log(messageData);
//       await socket.emit("Send_Message", messageData);
//       setMessageList((list) => [...list, message]);
//     }
//   };

//   useEffect(() => {
//     socket.on("Receive_Message", (message) => {
//       console.log(message);
//       setMessageList((list) => [...list, message]);
//     });
//   }, [socket]);

//   return (
//     <div className="chat-window">
//       <div className="chat-header">
//         <p>Live Chat</p>
//       </div>
//       <div className="chat-body">
//         {messageList.map((messageData) => {
//           return <h1>{messageData.message}</h1>;
//         })}
//       </div>
//       <div className="chat-footer">
//         <input
//           type="text"
//           placeholder="Hey..."
//           onChange={(event) => setMessage(event.target.value)}
//         />
//         <button onClick={onMessageSent}>&#9658;</button>
//       </div>
//     </div>
//   );
// }

// export default Chat;

import React, { useEffect, useState } from "react";
import ScrollToBottom from "react-scroll-to-bottom";

function Chat({ socket, student, studyGroup }) {
  const [currentMessage, setCurrentMessage] = useState("");
  const [chatList, setChatList] = useState([]);

  const onMessageSent = async () => {
    if (currentMessage !== "") {
      const currentTime = new Date(Date.now());
      const messageData = {
        group: studyGroup,
        student: student,
        message: currentMessage,
        // time:
        //   new Date(Date.now()).getHours() +
        //   ":" +
        //   new Date(Date.now()).getMinutes(),
        time: currentTime.getHours() + ":" + currentTime.getMinutes(),
      };

      await socket.emit("Send Message", messageData);
      setChatList((list) => [...list, messageData]);
      setCurrentMessage("");
    }
  };

  useEffect(() => {
    // console.log("In useEffect");
    // socket.on("Receive_Message", (data) => {
    //   setMessageList((list) => [...list, data]);
    //   socket.removeListener("Receive_Message");
    // });
    // console.log(messageList);
    socket.off("Receive Message").on("Receive Message", (data) => {
      // console.log(data,'recive');
      setChatList((list) => [...list, data]);
    });
  }, [socket]);

  return (
    <div className="chat-window">
      <div className="chat-header">
        <p>Group Chat</p>
      </div>
      <div className="chat-body">
        <ScrollToBottom className="message-container">
          {chatList.map((messageContent) => {
            return (
              <div
                className="message"
                id={student === messageContent.student ? "you" : "other"}
                key={messageContent.student}
              >
                <div>
                  <div className="message-content">
                    <p>{messageContent.message}</p>
                  </div>
                  <div className="message-meta">
                    <p id="time">{messageContent.time}</p>
                    <p id="student">{messageContent.student}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </ScrollToBottom>
      </div>
      <div className="chat-footer">
        <input
          type="text"
          value={currentMessage}
          placeholder="Message"
          onChange={(event) => {
            setCurrentMessage(event.target.value);
          }}
          onKeyDown={(event) => {
            event.key === "Enter" && onMessageSent();
          }}
        />
        <button onClick={onMessageSent}>&#9658;</button>
      </div>
    </div>
  );
}

export default Chat;
